"""Write SCAFFOLDED test stubs for edge cases that need human assertion.

A SCAFFOLDED test is a generated test that passed gates 1+2 (AST valid,
original) but stopped before gate 4 (ran against real code). The structure
is correct; the assertion needs a human to complete it.

Stub format:
  - Correct imports
  - Function signature matching the original
  - `# quell: complete assertion` comment in place of the assertion
  - Gate info in a docstring showing how far the test got
"""
from __future__ import annotations

import textwrap
from pathlib import Path

from quell.core.models import GeneratedTest, Requirement


def write_scaffold_stub(
    requirement: Requirement,
    test: GeneratedTest | None,
    gates_passed: int,
    scaffold_dir: Path,
) -> Path:
    """Write a scaffold stub for a SCAFFOLDED requirement and return its path.

    The stub is appended to `scaffold_dir / test_<module>.py`.
    Creates the file and parent directories if they don't exist.
    Adds `# quell: scaffold` header to new files.
    """
    scaffold_dir.mkdir(parents=True, exist_ok=True)

    module_name = (requirement.target_file.stem if requirement.target_file else "unknown")
    stub_file = scaffold_dir / f"test_{module_name}.py"

    stub_code = _build_stub(requirement, test, gates_passed)

    if not stub_file.exists():
        header = textwrap.dedent(f"""\
            # quell: scaffold — complete the assertions below and move to your test suite
            # Generated by Quell for: {requirement.target_file or 'unknown'}
            from __future__ import annotations

            import pytest


        """)
        stub_file.write_text(header + stub_code + "\n", encoding="utf-8")
    else:
        existing = stub_file.read_text(encoding="utf-8")
        func_name = _stub_function_name(requirement)
        if func_name not in existing:
            stub_file.write_text(existing + stub_code + "\n", encoding="utf-8")

    return stub_file


def _stub_function_name(requirement: Requirement) -> str:
    safe_fn = requirement.target_function.replace(".", "_").replace("<", "").replace(">", "")
    safe_id = requirement.id.replace("-", "_").replace(".", "_")
    return f"test_quell_scaffold_{safe_fn}_{safe_id}"


def _build_stub(
    requirement: Requirement,
    test: GeneratedTest | None,
    gates_passed: int,
) -> str:
    func_name = _stub_function_name(requirement)

    if test is not None:
        # Use the generated test code as a base, replacing the assertion
        lines = test.test_code.splitlines()
        stub_lines: list[str] = []
        in_assert = False
        for line in lines:
            stripped = line.strip()
            if stripped.startswith("assert ") or stripped.startswith("with pytest.raises"):
                if not in_assert:
                    stub_lines.append("    # quell: complete assertion")
                    stub_lines.append("    # Original generated assertion was:")
                    stub_lines.append(f"    #   {stripped}")
                    stub_lines.append("    pass  # TODO: replace with your assertion")
                    in_assert = True
            elif stripped.startswith("def test_"):
                # Rename the function to the scaffold name
                stub_lines.append(f"def {func_name}():")
                in_assert = False
            else:
                stub_lines.append(line)
                in_assert = False
        code = "\n".join(stub_lines)
    else:
        # No generated test — build a minimal stub
        target = requirement.target_function
        module = requirement.target_file.stem if requirement.target_file else "your_module"
        code = textwrap.dedent(f"""\
            def {func_name}():
                \"\"\"
                Quell scaffold — gates passed: {gates_passed}/5

                Constraint: {requirement.description}
                Source    : {requirement.target_file or 'unknown'}:{requirement.source_line or '?'}
                Kind      : {requirement.constraint_kind.value}
                \"\"\"
                from {module} import {target}
                # quell: complete assertion
                # TODO: call {target}() and assert the edge case behaviour
                pass
        """)

    return f"\n{code}\n"


def ensure_scaffold_gitignored(project_root: Path, scaffold_dir: Path) -> None:
    """Add scaffold_dir to .gitignore if not already present."""
    gitignore = project_root / ".gitignore"
    rel_path = str(scaffold_dir.relative_to(project_root)).replace("\\", "/") + "/"

    if gitignore.exists():
        content = gitignore.read_text(encoding="utf-8")
        if rel_path in content or scaffold_dir.name + "/" in content:
            return
        note = "\n# Quell scaffold stubs — complete assertions and move to test suite\n"
        gitignore.write_text(content + note + rel_path + "\n", encoding="utf-8")
    else:
        gitignore.write_text(f"# Quell scaffold stubs\n{rel_path}\n", encoding="utf-8")
