"""
Writes verified tests via libcst. Never string concatenation.
Always backs up. Always restores on failure. Always validates CST.
"""
from __future__ import annotations

import shutil
import time

import libcst as cst

from quell.core.models import AuditEntry, GeneratedTest, QuellConfig, VerificationStatus


class Writer:
    """Injects verified tests into test files using libcst AST injection."""

    def __init__(self, config: QuellConfig):
        self.config = config
        config.audit_log_path.parent.mkdir(parents=True, exist_ok=True)

    def write(self, test: GeneratedTest, req_id: str) -> bool:
        """Write a verified test to disk. Returns True on success."""
        f = test.test_file_path
        if not f.exists():
            f.parent.mkdir(parents=True, exist_ok=True)
            f.write_text("# Generated by Quell\nimport pytest\n\n", encoding="utf-8")

        bak = f.with_suffix(f".{int(time.time())}.bak")
        shutil.copy2(f, bak)

        try:
            new_src = self._inject(f.read_text(encoding="utf-8"), test.test_code)
            cst.parse_module(new_src)  # validate before writing
            f.write_text(new_src, encoding="utf-8")
            bak.unlink()
            self._log(AuditEntry(
                requirement_id=req_id, action="test_written",
                file_path=f,
                test_function_name=test.test_function_name,
                verification_status=VerificationStatus.VERIFIED,
            ))
            return True
        except Exception:
            if bak.exists():
                shutil.copy2(bak, f)
                bak.unlink()
            self._log(AuditEntry(
                requirement_id=req_id, action="write_failed", file_path=f,
            ))
            return False

    def _inject(self, existing: str, new_code: str) -> str:
        module = cst.parse_module(existing)
        new_stmts = cst.parse_module(new_code).body
        return module.with_changes(
            body=list(module.body) + list(new_stmts)
        ).code

    def _log(self, entry: AuditEntry) -> None:
        with self.config.audit_log_path.open("a") as f:
            f.write(entry.model_dump_json() + "\n")
