"""
Generates PySpark tests for NOT_NULL and TYPE_CHECK requirements.
Pure rule-based. No LLM. No network.

Generated tests use a shared SparkSession fixture from conftest.py.
Quell auto-generates conftest.py if not present.
"""
from __future__ import annotations

import re
from pathlib import Path

from quell.core.models import ConstraintKind, GeneratedTest, Requirement

VALID_VALUES: dict[str, str] = {
    "IntegerType": "1",
    "LongType":    "1",
    "FloatType":   "1.0",
    "DoubleType":  "1.0",
    "StringType":  '"test"',
    "BooleanType": "True",
    "ArrayType":   "[]",
    "MapType":     "{}",
}

PYSPARK_CONFTEST = '''"""SparkSession fixture — generated by Quell."""
import pytest
from pyspark.sql import SparkSession


@pytest.fixture(scope="session")
def spark():
    """Shared SparkSession. Session-scoped: created once, reused across all tests."""
    spark = (
        SparkSession.builder
        .master("local[*]")
        .appName("quell-pyspark-tests")
        .config("spark.sql.shuffle.partitions", "1")
        .config("spark.ui.enabled", "false")
        .getOrCreate()
    )
    spark.sparkContext.setLogLevel("ERROR")
    yield spark
    spark.stop()
'''


class PySparkRuleEngine:
    """Generates verified PySpark tests for NOT_NULL and TYPE_CHECK requirements."""

    def can_handle(self, req: Requirement) -> bool:
        return req.constraint_kind in {
            ConstraintKind.NOT_NULL,
            ConstraintKind.TYPE_CHECK,
        }

    def generate(self, req: Requirement) -> GeneratedTest | None:
        if req.constraint_kind == ConstraintKind.NOT_NULL:
            return self._not_null(req)
        if req.constraint_kind == ConstraintKind.TYPE_CHECK:
            return self._type_check(req)
        return None

    def ensure_conftest(self, test_dir: Path) -> None:
        """Auto-generate conftest.py with spark fixture if not present."""
        conftest = test_dir / "conftest.py"
        if conftest.exists():
            if "def spark" in conftest.read_text():
                return
            conftest.write_text(conftest.read_text() + "\n" + PYSPARK_CONFTEST)
        else:
            conftest.parent.mkdir(parents=True, exist_ok=True)
            conftest.write_text(PYSPARK_CONFTEST)

    def _name(self, req: Requirement) -> str:
        func = re.sub(r"[^a-z0-9_]", "_", req.target_function.lower())
        col = (req.violation_input or {}).get("column", "col")
        return f"test_quell_{func}_{req.constraint_kind.value}_{col}_{req.id[:6]}"

    def _test_file(self, req: Requirement) -> Path:
        return (
            req.target_file.parent.parent / "tests" /
            f"test_{req.target_file.stem}.py"
        )

    def _not_null(self, req: Requirement) -> GeneratedTest:
        col = (req.violation_input or {}).get("column", "col")
        if not col.isidentifier():
            raise ValueError(f"Invalid PySpark column name: {col!r}")
        name = self._name(req)
        code = f'''def {name}(spark):
    """Quell PySpark: column '{col}' must not be null — {req.raw_spec_text}"""
    import pytest
    from pyspark.sql import Row
    from pyspark.sql.utils import AnalysisException

    with pytest.raises((AnalysisException, Exception)):
        df = spark.createDataFrame([Row(**{{"{col}": None}})])
        df.show()  # triggers schema enforcement
'''
        return GeneratedTest(
            requirement_id=req.id,
            test_function_name=name,
            test_code=code,
            test_file_path=self._test_file(req),
            explanation=f"PySpark: '{col}' nullable=False — null must be rejected",
            generated_by="pyspark_rule_engine",
        )

    def _type_check(self, req: Requirement) -> GeneratedTest:
        col = (req.violation_input or {}).get("column", "col")
        type_name = (req.violation_input or {}).get("type", "StringType")
        if not col.isidentifier():
            raise ValueError(f"Invalid PySpark column name: {col!r}")
        if not type_name.isidentifier() or type_name not in VALID_VALUES:
            raise ValueError(f"Invalid PySpark type name: {type_name!r}")
        valid = VALID_VALUES.get(type_name, '"test"')
        name = self._name(req)
        code = f'''def {name}(spark):
    """Quell PySpark: column '{col}' must be {type_name} — {req.raw_spec_text}"""
    from pyspark.testing import assertSchemaEqual
    from pyspark.sql import Row
    from pyspark.sql.types import StructType, StructField, {type_name}

    df = spark.createDataFrame([Row(**{{"{col}": {valid}}})])
    expected = StructType([StructField("{col}", {type_name}())])
    assertSchemaEqual(df.select("{col}").schema, expected)
'''
        return GeneratedTest(
            requirement_id=req.id,
            test_function_name=name,
            test_code=code,
            test_file_path=self._test_file(req),
            explanation=f"PySpark: '{col}' must be {type_name}",
            generated_by="pyspark_rule_engine",
        )
