"""
Formats Quell CI results as GitHub PR comment markdown.

The comment is structured as:
  - Score header with delta indicator
  - Per-file table with grade badges
  - Collapsible section with verified test suggestions (if any)
  - Footer with quell.build link

The comment is idempotent — the bot updates its own previous comment
rather than posting a new one each push (identified by COMMENT_MARKER).
"""
from __future__ import annotations

from quell.ci.reporter import CIReport
from quell.score.calculator import ProjectScore

COMMENT_MARKER = "<!-- quell-bot -->"
QUELL_URL = "https://quell.build"


def format_pr_comment(
    report: CIReport,
    project_score: ProjectScore,
    verified_tests: list[dict] | None = None,
) -> str:
    """
    Build the full PR comment markdown string.

    Args:
        report: CIReport from the CI run.
        project_score: Final ProjectScore after fixes.
        verified_tests: Optional list of dicts with keys:
            {function_name, code, file_path, line, operator}

    Returns:
        Complete GitHub-flavoured markdown string, ready to post.
    """
    lines: list[str] = [COMMENT_MARKER, ""]

    # --- Score header ---
    pct = project_score.percentage
    delta = report.score_after - report.score_before
    delta_str = f"+{delta:.1%}" if delta >= 0 else f"{delta:.1%}"
    delta_icon = "📈" if delta >= 0 else "📉"

    if pct >= 80:
        badge = f"![score](https://img.shields.io/badge/quell%20score-{pct}%25-4c1?style=flat-square)"
    elif pct >= 60:
        badge = f"![score](https://img.shields.io/badge/quell%20score-{pct}%25-dfb317?style=flat-square)"
    else:
        badge = f"![score](https://img.shields.io/badge/quell%20score-{pct}%25-e05d44?style=flat-square)"

    lines += [
        f"## {badge}",
        "",
        f"{delta_icon} **{delta_str}** vs base &nbsp;|&nbsp; "
        f"**{report.fixed_count}** survivors fixed &nbsp;|&nbsp; "
        f"**{report.skipped_count}** skipped",
        "",
    ]

    # --- Per-file score table ---
    if project_score.files:
        lines += [
            "### File scores",
            "",
            "| File | Score | Grade | Killed / Total |",
            "|------|------:|:-----:|---------------:|",
        ]
        for fs in sorted(project_score.files, key=lambda f: f.quell_score):
            grade_emoji = {"A": "🟢", "B": "🟡", "C": "🟠", "F": "🔴"}.get(fs.grade, "⚪")
            lines.append(
                f"| `{fs.file_path}` | {fs.percentage}% "
                f"| {grade_emoji} {fs.grade} "
                f"| {fs.killed_mutants} / {fs.total_mutants} |"
            )
        lines.append("")

    # --- Verified test suggestions ---
    if verified_tests:
        lines += [
            "<details>",
            f"<summary>🧪 <strong>{len(verified_tests)} verified killing tests available</strong>"
            " — click to expand</summary>",
            "",
        ]
        for t in verified_tests:
            op = t.get("operator", "unknown")
            file_path = t.get("file_path", "")
            line_no = t.get("line", "?")
            fn_name = t.get("function_name", "")
            lines += [
                f"**`{file_path}:{line_no}`** — `{op}`"
                + (f" in `{fn_name}`" if fn_name else ""),
                "",
                "```python",
                t.get("code", "").strip(),
                "```",
                "",
            ]
        lines += ["</details>", ""]
    elif report.total_survivors > 0 and report.fixed_count == 0:
        lines += [
            "> ⚠️ **No verified killing tests could be generated** for the "
            f"{report.total_survivors} surviving mutants. "
            "They may be equivalent mutants.",
            "",
        ]

    # --- Threshold result ---
    tr = report.threshold_result
    if tr.threshold > 0:
        if tr.passed:
            lines += [f"✅ **Threshold met:** {tr.message}", ""]
        else:
            lines += [f"❌ **Threshold not met:** {tr.message}", ""]

    # --- Footer ---
    lines += [
        "---",
        f"*Generated by [Quell]({QUELL_URL}) — verified AI test synthesis. "
        f"[Docs]({QUELL_URL}/docs) · [Badge]({QUELL_URL}/docs/badge)*",
    ]

    return "\n".join(lines)


# ── v2.0.0: PRS-based PR comment (spec7 §2.6, §5.5) ─────────────────────────

QUELL_SITE = "https://quell.buildsbyshashank.tech"


def format_prs_comment(
    prs_score: int,
    prs_tier: str,
    prs_tier_label: str,
    written_count: int,
    scaffolded_count: int,
    flagged_count: int,
    total_edge_cases: int,
    avg_confidence: float,
    before_score: int | None = None,
) -> str:
    """Build a PR comment showing PRS + three-bucket summary (spec7 §2.3, §2.6).

    Returns GitHub-flavoured markdown. Idempotent via COMMENT_MARKER.
    """
    tier_emoji = {"green": "🟢", "yellow": "🟡", "red": "🔴"}.get(prs_tier, "⚪")
    coverage_pct = (
        int((written_count + scaffolded_count) / total_edge_cases * 100)
        if total_edge_cases else 0
    )

    delta_str = ""
    if before_score is not None:
        delta = prs_score - before_score
        sign = "+" if delta >= 0 else ""
        delta_str = f"  ▲ {sign}{delta} (was {before_score} before run)"

    lines: list[str] = [
        COMMENT_MARKER,
        "",
        f"## {tier_emoji} Quell PRS: {prs_score}/100 — {prs_tier_label}{delta_str}",
        "",
        "| Bucket | Count | Detail |",
        "|--------|------:|--------|",
        f"| ✓ WRITTEN | {written_count} | Tests passed all 5 gates, ready to ship |",
        f"| ⚠ SCAFFOLDED | {scaffolded_count} | Structure written, assertion needed |",
        f"| 🚩 FLAGGED | {flagged_count} | Cannot auto-test — reason provided |",
        "",
        f"**Edge Case Coverage:** {coverage_pct}%"
        f" ({written_count + scaffolded_count} of {total_edge_cases} handled)",
    ]

    if written_count and avg_confidence:
        lines.append(
            f"**Avg Test Confidence:** {avg_confidence:.0f}%"
            f" (across {written_count} WRITTEN tests)"
        )

    lines += [
        "",
        "---",
        f"*[Quell]({QUELL_SITE}) — edge case finder. "
        f"[Docs]({QUELL_SITE}/docs)*",
    ]
    return "\n".join(lines)
